language: ruby
rvm:
  - 2.6.3
cache: bundler

before_install:
  # Install the right version of Bundler
  # from https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
  - bundle config set deployment 'true'

install:
  - make install

script:
  - ./bin/ci-build.sh

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _site
  target-branch: gh-pages
  fqdn: mickaelflochlay.com
  on:
    branch: master
