title: "Mick F"
description: > # this means to ignore newlines until "baseurl:"
  Mick F’s personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mickaelflochlay.com" # the base hostname & protocol for your site
twitter_username: dirtyhenry
github_username: dirtyhenry
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
permalink: /:categories/:title.html

# Micro.blog
microblog_title: "Mick F Micro.blog"
microblog_description: "..."

# Build settings
markdown: kramdown
theme: kids

menu:
  item0:
    title: Resume
    path: /resume.html

submenus:
  cv:
    item0:
      title: Expériences
      path: "#experienceAnchor"
    item1:
      title: Compétences
      path: "#skillsAnchor"
    item2:
      title: Formation
      path: "#trainingAnchor"
    item3:
      title: Loisirs
      path: "#miscAnchor"
    item4:
      title: Contact
      path: "#contactAnchor"
  resume:
    item0:
      title: Experience
      path: "#experienceAnchor"
    item1:
      title: Skills
      path: "#skillsAnchor"
    item2:
      title: Education
      path: "#trainingAnchor"
    item3:
      title: Interests
      path: "#miscAnchor"
    item4:
      title: Contact
      path: "#contactAnchor"

sass:
  load_paths:
    - _sass

plugins:
  - jekyll-sitemap

header_pages:
  - resume/index.html
